//! Translation between native key representations and ShareClick's portable
//! [`Key`]. Capture uses [`from_rdev`]; injection uses [`to_enigo`].

use shareclick_protocol::Key;

/// Map an `rdev` key (as seen by the capturing server) into a portable [`Key`].
#[cfg(feature = "native")]
pub fn from_rdev(k: rdev::Key) -> Key {
    use rdev::Key as R;
    match k {
        R::KeyA => Key::A,
        R::KeyB => Key::B,
        R::KeyC => Key::C,
        R::KeyD => Key::D,
        R::KeyE => Key::E,
        R::KeyF => Key::F,
        R::KeyG => Key::G,
        R::KeyH => Key::H,
        R::KeyI => Key::I,
        R::KeyJ => Key::J,
        R::KeyK => Key::K,
        R::KeyL => Key::L,
        R::KeyM => Key::M,
        R::KeyN => Key::N,
        R::KeyO => Key::O,
        R::KeyP => Key::P,
        R::KeyQ => Key::Q,
        R::KeyR => Key::R,
        R::KeyS => Key::S,
        R::KeyT => Key::T,
        R::KeyU => Key::U,
        R::KeyV => Key::V,
        R::KeyW => Key::W,
        R::KeyX => Key::X,
        R::KeyY => Key::Y,
        R::KeyZ => Key::Z,
        R::Num0 => Key::Num0,
        R::Num1 => Key::Num1,
        R::Num2 => Key::Num2,
        R::Num3 => Key::Num3,
        R::Num4 => Key::Num4,
        R::Num5 => Key::Num5,
        R::Num6 => Key::Num6,
        R::Num7 => Key::Num7,
        R::Num8 => Key::Num8,
        R::Num9 => Key::Num9,
        R::F1 => Key::F1,
        R::F2 => Key::F2,
        R::F3 => Key::F3,
        R::F4 => Key::F4,
        R::F5 => Key::F5,
        R::F6 => Key::F6,
        R::F7 => Key::F7,
        R::F8 => Key::F8,
        R::F9 => Key::F9,
        R::F10 => Key::F10,
        R::F11 => Key::F11,
        R::F12 => Key::F12,
        R::Escape => Key::Escape,
        R::Tab => Key::Tab,
        R::CapsLock => Key::CapsLock,
        R::Space => Key::Space,
        R::Backspace => Key::Backspace,
        R::Return => Key::Enter,
        R::Delete => Key::Delete,
        R::Insert => Key::Insert,
        R::Home => Key::Home,
        R::End => Key::End,
        R::PageUp => Key::PageUp,
        R::PageDown => Key::PageDown,
        R::LeftArrow => Key::Left,
        R::RightArrow => Key::Right,
        R::UpArrow => Key::Up,
        R::DownArrow => Key::Down,
        R::Minus => Key::Minus,
        R::Equal => Key::Equal,
        R::LeftBracket => Key::LeftBracket,
        R::RightBracket => Key::RightBracket,
        R::BackSlash => Key::Backslash,
        R::SemiColon => Key::Semicolon,
        R::Quote => Key::Quote,
        R::BackQuote => Key::Backquote,
        R::Comma => Key::Comma,
        R::Dot => Key::Dot,
        R::Slash => Key::Slash,
        R::ShiftLeft => Key::LShift,
        R::ShiftRight => Key::RShift,
        R::ControlLeft => Key::LCtrl,
        R::ControlRight => Key::RCtrl,
        R::Alt => Key::LAlt,
        R::AltGr => Key::RAlt,
        R::MetaLeft => Key::LMeta,
        R::MetaRight => Key::RMeta,
        R::Unknown(code) => Key::Unknown(code),
        _ => Key::Unknown(0),
    }
}

/// Map a portable [`Key`] into an `enigo` key for injection on the client.
#[cfg(feature = "native")]
pub fn to_enigo(k: Key) -> Option<enigo::Key> {
    use enigo::Key as E;
    let ch = |c: char| Some(E::Unicode(c));
    Some(match k {
        Key::A => return ch('a'),
        Key::B => return ch('b'),
        Key::C => return ch('c'),
        Key::D => return ch('d'),
        Key::E => return ch('e'),
        Key::F => return ch('f'),
        Key::G => return ch('g'),
        Key::H => return ch('h'),
        Key::I => return ch('i'),
        Key::J => return ch('j'),
        Key::K => return ch('k'),
        Key::L => return ch('l'),
        Key::M => return ch('m'),
        Key::N => return ch('n'),
        Key::O => return ch('o'),
        Key::P => return ch('p'),
        Key::Q => return ch('q'),
        Key::R => return ch('r'),
        Key::S => return ch('s'),
        Key::T => return ch('t'),
        Key::U => return ch('u'),
        Key::V => return ch('v'),
        Key::W => return ch('w'),
        Key::X => return ch('x'),
        Key::Y => return ch('y'),
        Key::Z => return ch('z'),
        Key::Num0 => return ch('0'),
        Key::Num1 => return ch('1'),
        Key::Num2 => return ch('2'),
        Key::Num3 => return ch('3'),
        Key::Num4 => return ch('4'),
        Key::Num5 => return ch('5'),
        Key::Num6 => return ch('6'),
        Key::Num7 => return ch('7'),
        Key::Num8 => return ch('8'),
        Key::Num9 => return ch('9'),
        Key::F1 => E::F1,
        Key::F2 => E::F2,
        Key::F3 => E::F3,
        Key::F4 => E::F4,
        Key::F5 => E::F5,
        Key::F6 => E::F6,
        Key::F7 => E::F7,
        Key::F8 => E::F8,
        Key::F9 => E::F9,
        Key::F10 => E::F10,
        Key::F11 => E::F11,
        Key::F12 => E::F12,
        Key::Escape => E::Escape,
        Key::Tab => E::Tab,
        Key::CapsLock => E::CapsLock,
        Key::Space => E::Space,
        Key::Backspace => E::Backspace,
        Key::Enter => E::Return,
        Key::Delete => E::Delete,
        Key::Insert => return None,
        Key::Home => E::Home,
        Key::End => E::End,
        Key::PageUp => E::PageUp,
        Key::PageDown => E::PageDown,
        Key::Left => E::LeftArrow,
        Key::Right => E::RightArrow,
        Key::Up => E::UpArrow,
        Key::Down => E::DownArrow,
        Key::Minus => return ch('-'),
        Key::Equal => return ch('='),
        Key::LeftBracket => return ch('['),
        Key::RightBracket => return ch(']'),
        Key::Backslash => return ch('\\'),
        Key::Semicolon => return ch(';'),
        Key::Quote => return ch('\''),
        Key::Backquote => return ch('`'),
        Key::Comma => return ch(','),
        Key::Dot => return ch('.'),
        Key::Slash => return ch('/'),
        Key::LShift | Key::RShift => E::Shift,
        Key::LCtrl | Key::RCtrl => E::Control,
        Key::LAlt => E::Alt,
        Key::RAlt => E::Alt,
        Key::LMeta | Key::RMeta => E::Meta,
        Key::Unknown(_) => return None,
    })
}
